apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  # NodePort is used for local Minikube testing. 
  # Change to LoadBalancer when moving to DigitalOcean.
  type: NodePort 
  selector:
    app: hello-world-app # Connects this service to pods with this label
  ports:
    - protocol: TCP
      port: 80         # Port users visit (e.g., http://localhost)
      targetPort: 3000 # Port where the Next.js app is actually running